---
- hosts: localhost
  tasks:
  - name: task1
    command: date
    notify: one
  - name: task2
    shell: uname
    notify: one
  - name: task3
    debug: msg="OK"
  - name: task4
    debug: msg="OK"
  handlers:
  - name: one
    debug: msg="Handler block - 1"
  - name: two
    debug: msg="Handler block - 2"
