---
- hosts: localhost
  tasks:
  - name: task1
    command: echo "OK"
    notify: call-1
  - name: task2
    command: echo "OK"
    notify: call-2
  - name: task3
    command: echo "OK"
    notify: call-3
  handlers:
  - name: one
    debug: msg="Thank you-1"
    listen: call-1
  - name: two
    debug: msg="Thank you-2"
    listen: call-2
  - debug: msg="Thank you-3"
    listen: call-3
