---
- hosts: node1
  tasks:
  - name: add some content to /tmp/IP1.conf
    blockinfile:
      path: /tmp/IP1.conf
      block: |
       # adding new content
       Field1 = "Value1"
       Field2 = "Value2"
       Field3 = true
