---
- hosts: node1
  vars:
  - netproperty: {TYPE: Ethernet,onboot: yes,bootproto: dhcp,defroute: yes}
  tasks:
  - name: create a new network property config file
    template: src=file3.j2 dest=/tmp/net.conf
