---
- hosts: localhost
  tasks:
  - name: block execution
    block:
    - name: task1 
      command: /bin/true
    - name: task2
      command: /bin/false
    - name: task3
      command: /bin/true
    rescue:
    - name: Handle the errors 
      debug: msg="recue block"
  - name: outside the block
    debug: msg="rese block"
