---
- hosts: node1
  tasks:
  - name: task1 wait until port 80 is active
    wait_for:
      port: 80
      state: started
      delay: 20
  - name: task2
    debug: msg="OK-2"
  - name: task3
    debug: msg="OK-3"
