---
- hosts: node1
  tasks:
  - name: task1 wait until port 80 is active
    wait_for:
      port: 80
      state: started
      timeout: 5 # wait for 5 secs 
      delay: 10
    ignore_errors: true
  - name: task2
    debug: msg="OK-2"
  - name: task3
    debug: msg="OK-3"
