---
- hosts: node1
  tasks:
  - name: task1 wait until port 80 is In-active
    wait_for:
      port: 80
      state: stopped #<== stopped state
      timeout: 15 # wait for 15 secs 
    ignore_errors: true
  - name: task2
    debug: msg="OK-2"
  - name: task3
    debug: msg="OK-3"
