---
- hosts: node1
  tasks:
  - name: task1-wait until the file /tmp/r1.log is exists
    wait_for:
      path: /tmp/r1.log
      timeout: 25
    ignore_errors: yes
  - name: task2
    debug: msg="OK-2"
  - name: task3
    debug: msg="OK-3"
