---
- hosts: node1
  tasks:
  - name: task1-wait until the search pattern should match from inputfile
    wait_for:
      path: /tmp/r2.log
      search_regex: tcsh
      timeout: 25
    ignore_errors: yes
  - name: task2
    debug: msg="OK-2"
  - name: task3
    debug: msg="OK-3"
