---
- hosts: localhost
  tasks:
  - name: task1 
    command: echo "OK-1"
    notify: call-one # if state is changed invoke handler block
  - name: task2
    debug: msg="OK-2"
  - name: task3
    debug: msg="OK-3"
  - name: task4
    shell: echo "OK-4"
  handlers:
  - name: call-one
    debug: msg="This is Handler block"
