---
- hosts: localhost
  tasks:
  - set_fact:
      user: 'host01@oracle.com'
  - debug:
      msg: "{{user|regex_search('[a-z]+')}}" # match 1 or more lowercase chars
  - debug:
      msg: "{{user|regex_replace('host','demo')}}"
  - set_fact:
      info: "server IPs are 10.20.30.40 and 192.168.1.5 and more"
  - debug:
      msg: "{{info|regex_findall('\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b')}}"

