---
- hosts: node1
  tasks:
  - name: task1
    debug: msg="OK1"
  - name: task2
    command: sleep 3 # task execution is 3secs
    async: 10
    poll: 0
    register: result
  - name: check the job status
    async_status:
      jid: "{{result.ansible_job_id}}"
    register: job_result
    until: job_result.finished
    retries: 5 
  - name: task3
    debug: msg="OK2"
  - debug: var=result
