---
- name: install a package 
  hosts: localhost
  vars:
   pkg: zsh
  tasks:
  - name: task1- install a package
    yum:
     name: "{{pkg}}"
     state: installed
    register: result
  - debug: msg="pacakge {{pkg}} installation status {{result.rc}}"
